/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LabsThirdRouteImport } from './routes/labs/third'
import { Route as LabsSecondRouteImport } from './routes/labs/second'
import { Route as LabsFirstRouteImport } from './routes/labs/first'

const LabsThirdRoute = LabsThirdRouteImport.update({
  id: '/labs/third',
  path: '/labs/third',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsSecondRoute = LabsSecondRouteImport.update({
  id: '/labs/second',
  path: '/labs/second',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsFirstRoute = LabsFirstRouteImport.update({
  id: '/labs/first',
  path: '/labs/first',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/labs/first': typeof LabsFirstRoute
  '/labs/second': typeof LabsSecondRoute
  '/labs/third': typeof LabsThirdRoute
}
export interface FileRoutesByTo {
  '/labs/first': typeof LabsFirstRoute
  '/labs/second': typeof LabsSecondRoute
  '/labs/third': typeof LabsThirdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/labs/first': typeof LabsFirstRoute
  '/labs/second': typeof LabsSecondRoute
  '/labs/third': typeof LabsThirdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/labs/first' | '/labs/second' | '/labs/third'
  fileRoutesByTo: FileRoutesByTo
  to: '/labs/first' | '/labs/second' | '/labs/third'
  id: '__root__' | '/labs/first' | '/labs/second' | '/labs/third'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LabsFirstRoute: typeof LabsFirstRoute
  LabsSecondRoute: typeof LabsSecondRoute
  LabsThirdRoute: typeof LabsThirdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/labs/third': {
      id: '/labs/third'
      path: '/labs/third'
      fullPath: '/labs/third'
      preLoaderRoute: typeof LabsThirdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/second': {
      id: '/labs/second'
      path: '/labs/second'
      fullPath: '/labs/second'
      preLoaderRoute: typeof LabsSecondRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/first': {
      id: '/labs/first'
      path: '/labs/first'
      fullPath: '/labs/first'
      preLoaderRoute: typeof LabsFirstRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LabsFirstRoute: LabsFirstRoute,
  LabsSecondRoute: LabsSecondRoute,
  LabsThirdRoute: LabsThirdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
